import json

from odoo import api, fields, models


class ChatroomAIOptimizationRun(models.Model):
    _name = "chatroom.ai.optimization.run"
    _description = "AI Optimization Run Record"
    _order = "create_date desc"

    optimizer_id = fields.Many2one(
        "chatroom.ai.prompt.optimizer",
        required=True,
        ondelete="cascade",
        index=True,
    )
    agent_id = fields.Many2one(
        related="optimizer_id.agent_id",
        store=True,
        readonly=True,
    )

    state = fields.Selection(
        [
            ("running", "Running"),
            ("completed", "Completed"),
            ("failed", "Failed"),
        ],
        default="running",
        required=True,
    )

    start_date = fields.Datetime(
        required=True,
        default=fields.Datetime.now,
    )
    end_date = fields.Datetime()

    test_scenarios = fields.Text(
        string="Test Scenarios (JSON)",
        help="The scenarios used for testing",
    )
    test_scenarios_pretty = fields.Text(
        string="Test Scenarios",
        compute="_compute_results_summaries",
        readonly=True,
    )
    current_results_summary = fields.Text(
        compute="_compute_results_summaries",
        readonly=True,
    )
    best_results_summary = fields.Text(
        compute="_compute_results_summaries",
        readonly=True,
    )
    conversations_tested = fields.Integer(
        readonly=True,
    )

    current_prompt = fields.Text(
        readonly=True,
        help="The prompt that was being used before optimization",
    )
    improved_prompt = fields.Text(
        readonly=True,
        help="The new prompt generated by the optimizer",
    )

    current_score = fields.Float(
        string="Current Prompt Score",
        readonly=True,
    )
    new_score = fields.Float(
        string="New Prompt Score",
        readonly=True,
    )
    improvement = fields.Float(
        readonly=True,
        help="Score difference (new - current)",
    )

    result = fields.Selection(
        [
            ("test_only", "Test Only"),
            ("improved", "Improved"),
            ("no_improvement", "No Improvement"),
        ],
    )

    analysis_notes = fields.Text(
        string="Performance Analysis",
        help="AI-generated analysis of problems",
    )

    error_message = fields.Text()

    @api.depends("test_scenarios")
    def _compute_results_summaries(self):
        def _format_scenarios(scenarios):
            cleaned = [str(s).strip() for s in (scenarios or []) if str(s).strip()]
            if not cleaned:
                return "No scenarios available"
            return "\n".join(
                f"{idx}. {scenario}" for idx, scenario in enumerate(cleaned, 1)
            )

        def _format_items(items):
            lines = []
            for idx, item in enumerate(items or [], 1):
                scenario_number = item.get("scenario_number") or idx
                scenario_text = (item.get("scenario") or "").strip()
                quality = item.get("quality_score")
                turns = item.get("turns_completed")
                helpful = item.get("helpful")
                appropriate = item.get("appropriate")
                notes = (item.get("notes") or "").strip()

                lines.append(f"Scenario {scenario_number}")
                if scenario_text:
                    lines.append(f"- Prompt: {scenario_text}")
                lines.append(f"- Quality: {quality}")
                lines.append(f"- Turns completed: {turns}")
                lines.append(f"- Helpful: {helpful} | Appropriate: {appropriate}")
                if notes:
                    lines.append(f"- Notes: {notes}")
                lines.append("")

            return "\n".join(lines).strip() or "No scenario results available"

        for run in self:
            run.test_scenarios_pretty = "No scenarios available"
            run.current_results_summary = "No scenario results available"
            run.best_results_summary = "No scenario results available"

            if not run.test_scenarios:
                continue

            try:
                payload = json.loads(run.test_scenarios)
            except Exception:
                raw = (run.test_scenarios or "").strip()
                if raw:
                    run.test_scenarios_pretty = raw
                continue

            if isinstance(payload, dict):
                run.test_scenarios_pretty = _format_scenarios(payload.get("scenarios"))
                run.current_results_summary = _format_items(
                    payload.get("current_results")
                )
                run.best_results_summary = _format_items(payload.get("best_results"))
            elif isinstance(payload, list):
                run.test_scenarios_pretty = _format_scenarios(payload)

    def action_apply_improved_prompt(self):
        self.ensure_one()

        if not self.improved_prompt:
            return {
                "type": "ir.actions.client",
                "tag": "display_notification",
                "params": {
                    "title": "No Improved Prompt",
                    "message": "This run does not have an improved prompt to apply.",
                    "type": "warning",
                },
            }

        self.agent_id.write({"system_prompt": self.improved_prompt})

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": "Prompt Applied!",
                "message": (
                    f"The improved prompt has been applied to {self.agent_id.name}"
                ),
                "type": "success",
            },
        }
