from odoo import fields, models


class ChatroomAIOptimizationRun(models.Model):
    _name = "chatroom.ai.optimization.run"
    _description = "AI Optimization Run Record"
    _order = "create_date desc"

    optimizer_id = fields.Many2one(
        "chatroom.ai.prompt.optimizer",
        required=True,
        ondelete="cascade",
        index=True,
    )
    agent_id = fields.Many2one(
        related="optimizer_id.agent_id",
        store=True,
        readonly=True,
    )

    state = fields.Selection(
        [
            ("running", "Running"),
            ("completed", "Completed"),
            ("failed", "Failed"),
        ],
        default="running",
        required=True,
    )

    start_date = fields.Datetime(
        required=True,
        default=fields.Datetime.now,
    )
    end_date = fields.Datetime()

    test_scenarios = fields.Text(
        string="Test Scenarios (JSON)",
        help="The scenarios used for testing",
    )
    conversations_tested = fields.Integer(
        readonly=True,
    )

    current_prompt = fields.Text(
        readonly=True,
        help="The prompt that was being used before optimization",
    )
    improved_prompt = fields.Text(
        readonly=True,
        help="The new prompt generated by the optimizer",
    )

    current_score = fields.Float(
        string="Current Prompt Score",
        readonly=True,
    )
    new_score = fields.Float(
        string="New Prompt Score",
        readonly=True,
    )
    improvement = fields.Float(
        readonly=True,
        help="Score difference (new - current)",
    )

    result = fields.Selection(
        [
            ("test_only", "Test Only"),
            ("improved", "Improved"),
            ("no_improvement", "No Improvement"),
        ],
    )

    analysis_notes = fields.Text(
        string="Performance Analysis",
        help="AI-generated analysis of problems",
    )

    error_message = fields.Text()

    def action_apply_improved_prompt(self):
        self.ensure_one()

        if not self.improved_prompt:
            return {
                "type": "ir.actions.client",
                "tag": "display_notification",
                "params": {
                    "title": "No Improved Prompt",
                    "message": "This run does not have an improved prompt to apply.",
                    "type": "warning",
                },
            }

        self.agent_id.write({"system_prompt": self.improved_prompt})

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": "Prompt Applied!",
                "message": (
                    f"The improved prompt has been applied to {self.agent_id.name}"
                ),
                "type": "success",
            },
        }
