"""Extension of chatroom.message for AI processing"""

import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class ChatroomMessage(models.Model):
    _inherit = "chatroom.message"

    is_ai_generated = fields.Boolean(
        string="AI Generated",
        default=False,
        help="True if this message was generated by an AI agent",
    )
    ai_pending_processing = fields.Boolean(
        string="AI Pending Processing",
        default=False,
        index=True,
        copy=False,
        help="Message waiting to be processed by AI",
    )

    @api.model_create_multi
    def create(self, vals_list):
        messages = super().create(vals_list)

        incoming_messages = messages.filtered(
            lambda m: m.direction == "incoming" and not m.is_internal
        )

        if incoming_messages:
            incoming_messages.write({"ai_pending_processing": True})

            self.env.ref("chatroom_ai.ir_cron_process_ai_messages")._trigger()

        return messages

    @api.model
    def _cron_process_ai_messages(self, limit=50):
        domain = [("ai_pending_processing", "=", True)]
        pending_messages = self.search(domain, limit=limit, order="create_date asc")

        if not pending_messages:
            return

        _logger.info("Processing %s pending AI messages", len(pending_messages))

        for message in pending_messages:
            try:
                message.ai_pending_processing = False

                message._process_with_ai_agents(message)

            except Exception as e:
                _logger.error(
                    f"Error processing AI message {message.id}: {e}", exc_info=True
                )

        if self.search_count(domain, limit=1):
            self.env.ref("chatroom_ai.ir_cron_process_ai_messages")._trigger()

    def _process_with_ai_agents(self, message):
        room = message.room_id

        if room.ai_enabled and room.ai_agent_id:
            room.ai_agent_id.process_incoming_message(message)
        else:
            agents = self.env["chatroom.ai.agent"].search(
                [
                    ("active", "=", True),
                ]
            )

            for agent in agents:
                if agent.should_respond_to_room(room):
                    agent.process_incoming_message(message)
                    break

    def _get_message_text_with_author(self):
        self.ensure_one()

        if self.is_ai_generated:
            return self.body

        return super()._get_message_text_with_author()

    def _notify_message_created(self):
        self.ensure_one()

        payload = {
            "id": self.id,
            "room_id": self.room_id.id,
            "body": self.body,
            "direction": self.direction,
            "author_name": self.author_name,
            "message_type": self.message_type,
            "create_date": self.create_date.isoformat() if self.create_date else False,
            "is_internal": self.is_internal,
            "is_ai_generated": self.is_ai_generated,
        }

        self.env.cr.execute(
            """
            SELECT DISTINCT uid
            FROM res_groups_users_rel
            WHERE gid IN %s
        """,
            (
                tuple(
                    [
                        self.env.ref("chatroom.group_chatroom_user").id,
                        self.env.ref("chatroom.group_chatroom_manager").id,
                    ]
                ),
            ),
        )
        user_ids = [row[0] for row in self.env.cr.fetchall()]
        users_to_notify = self.env["res.users"].browse(user_ids)

        managers = users_to_notify.filtered(
            lambda u: u.has_group("chatroom.group_chatroom_manager")
        )

        regular_users = users_to_notify - managers
        if self.room_id.assigned_to_id:
            regular_users = regular_users.filtered(
                lambda u: u.id == self.room_id.assigned_to_id.id
            )

        for user in managers | regular_users:
            if user.partner_id:
                user.partner_id._bus_send("chatroom/message_created", payload)

        self.room_id._notify_room_updated()
