import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class ChatroomMessage(models.Model):
    _inherit = "chatroom.message"

    is_ai_generated = fields.Boolean(
        string="AI Generated",
        default=False,
        help="True if this message was generated by an AI agent",
    )
    ai_pending_processing = fields.Boolean(
        string="AI Pending Processing",
        default=False,
        index=True,
        copy=False,
        help="Message waiting to be processed by AI",
    )
    ai_processing_state = fields.Selection(
        [
            ("pending", "Pending"),
            ("processing", "Processing"),
            ("completed", "Completed"),
            ("failed", "Failed"),
        ],
        string="AI Processing State",
        default="pending",
        index=True,
        copy=False,
        help="Current state of AI processing for this message",
    )
    ai_processing_date = fields.Datetime(
        string="AI Processing Date",
        copy=False,
        help="Date when the message was last processed by AI",
    )
    ai_processing_error = fields.Text(
        string="AI Processing Error",
        copy=False,
        help="Last error encountered during AI processing",
    )

    @api.model_create_multi
    def create(self, vals_list):
        messages = super().create(vals_list)

        incoming_messages = messages.filtered(
            lambda m: m.direction == "incoming" and not m.is_internal
        )

        if incoming_messages:
            incoming_messages.write(
                {
                    "ai_pending_processing": True,
                    "ai_processing_state": "pending",
                }
            )

            batch_delay = int(
                self.env["ir.config_parameter"]
                .sudo()
                .get_param("chatroom.ai_message_batch_delay", default="15")
            )

            for room in incoming_messages.mapped("room_id"):
                room_messages = incoming_messages.filtered(
                    lambda m, r=room: m.room_id == r
                )
                last_message = room_messages.sorted("create_date", reverse=True)[0]
                last_message.with_delay(
                    eta=batch_delay,
                    max_retries=2,
                    identity_key=f"ai_process_room_{room.id}",
                    channel="root.ai",
                    description=self.env._(
                        "Process AI messages for room %(room_name)s",
                        room_name=room.name,
                    ),
                )._job_process_room_messages()

        return messages

    def _job_process_room_messages(self):
        self.ensure_one()
        room = self.room_id

        if not room.ai_enabled:
            return

        room_messages = self.search(
            [
                ("room_id", "=", room.id),
                ("ai_processing_state", "in", ["pending", "failed"]),
            ],
            order="create_date asc",
        )

        if not room_messages:
            return

        processing_count = self.search_count(
            [
                ("room_id", "=", room.id),
                ("ai_processing_state", "=", "processing"),
            ]
        )

        if processing_count > 0:
            return

        try:
            room_messages.write(
                {
                    "ai_processing_state": "processing",
                    "ai_processing_date": fields.Datetime.now(),
                }
            )

            last_message = room_messages.sorted("create_date", reverse=True)[0]
            last_message._process_with_ai_agents(last_message)

            room_messages.write(
                {
                    "ai_pending_processing": False,
                    "ai_processing_state": "completed",
                    "ai_processing_error": False,
                }
            )

        except Exception as e:
            error_msg = str(e)
            _logger.error(
                f"Error processing AI messages for room {room.id}: {error_msg}",
                exc_info=True,
            )

            room_messages.write(
                {
                    "ai_processing_state": "failed",
                    "ai_processing_error": error_msg[:500],
                    "ai_pending_processing": False,
                }
            )

            room.write({"needs_attention": True})
            raise

    def _process_with_ai_agents(self, message):
        room = message.room_id

        if room.ai_enabled and room.ai_agent_id:
            room.ai_agent_id.process_incoming_message(message)
        else:
            agents = self.env["chatroom.ai.agent"].search(
                [
                    ("active", "=", True),
                ]
            )

            for agent in agents:
                if agent.should_respond_to_room(room):
                    agent.process_incoming_message(message)
                    break

    def _get_message_text_with_author(self):
        self.ensure_one()

        if self.is_ai_generated:
            return self.body

        return super()._get_message_text_with_author()

    def _notify_message_created(self):
        self.ensure_one()

        payload = {
            "id": self.id,
            "room_id": self.room_id.id,
            "body": self.body,
            "direction": self.direction,
            "author_name": self.author_name,
            "message_type": self.message_type,
            "create_date": self.create_date.isoformat() if self.create_date else False,
            "is_internal": self.is_internal,
            "is_ai_generated": self.is_ai_generated,
        }

        try:
            chatroom_users = self.env.ref("chatroom.group_chatroom_user").all_user_ids
        except Exception as e:
            _logger.error(f"Error getting chatroom users: {e}")
            chatroom_users = self.env["res.users"]

        try:
            chatroom_managers = self.env.ref(
                "chatroom.group_chatroom_manager"
            ).all_user_ids
        except Exception as e:
            _logger.error(f"Error getting chatroom managers: {e}")
            chatroom_managers = self.env["res.users"]

        users_to_notify = chatroom_managers
        if self.room_id.assigned_to_id:
            if self.room_id.assigned_to_id in chatroom_users:
                users_to_notify |= self.room_id.assigned_to_id
        else:
            users_to_notify |= chatroom_users - chatroom_managers

        notified_partners = set()
        for user in users_to_notify:
            if user.partner_id and user.partner_id.id not in notified_partners:
                notified_partners.add(user.partner_id.id)
                user.partner_id._bus_send("chatroom/message_created", payload)

        self.room_id._notify_room_updated()
