import datetime
import logging

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class ChatroomMessage(models.Model):
    _inherit = "chatroom.message"

    is_ai_generated = fields.Boolean(
        string="AI Generated",
        default=False,
        help="True if this message was generated by an AI agent",
    )
    ai_pending_processing = fields.Boolean(
        string="AI Pending Processing",
        default=False,
        index=True,
        copy=False,
        help="Message waiting to be processed by AI",
    )
    ai_processing_state = fields.Selection(
        [
            ("pending", "Pending"),
            ("processing", "Processing"),
            ("completed", "Completed"),
            ("failed", "Failed"),
        ],
        string="AI Processing State",
        default="pending",
        index=True,
        copy=False,
        help="Current state of AI processing for this message",
    )
    ai_processing_date = fields.Datetime(
        string="AI Processing Date",
        copy=False,
        help="Date when the message was last processed by AI",
    )
    ai_processing_error = fields.Text(
        string="AI Processing Error",
        copy=False,
        help="Last error encountered during AI processing",
    )

    is_transcribing = fields.Boolean(
        "Transcribing",
        default=False,
    )
    is_transcribed = fields.Boolean(
        "Transcribed by AI",
        default=False,
    )
    is_transcription_failed = fields.Boolean(
        "Transcription Failed",
        default=False,
    )

    @api.model_create_multi
    def create(self, vals_list):
        messages = super().create(vals_list)

        incoming_messages = messages.filtered(
            lambda m: m.direction == "incoming" and not m.is_internal
        )

        if incoming_messages:
            incoming_messages.write(
                {
                    "ai_pending_processing": True,
                    "ai_processing_state": "pending",
                }
            )

            batch_delay = int(
                self.env["ir.config_parameter"]
                .sudo()
                .get_param("chatroom.ai_message_batch_delay", default="15")
            )

            for room in incoming_messages.mapped("room_id"):
                room_messages = incoming_messages.filtered(
                    lambda m, r=room: m.room_id == r
                )
                last_message = room_messages.sorted("create_date", reverse=True)[0]

                identity_key = f"ai_process_room_{room.id}"
                existing_job = (
                    self.env["queue.job"]
                    .sudo()
                    .search(
                        [
                            ("identity_key", "=", identity_key),
                            ("state", "in", ["pending", "enqueued"]),
                        ],
                        limit=1,
                    )
                )

                if existing_job:
                    new_eta = fields.Datetime.now() + datetime.timedelta(
                        seconds=batch_delay
                    )
                    existing_job.write({"eta": new_eta})
                else:
                    last_message.with_delay(
                        eta=batch_delay,
                        max_retries=2,
                        identity_key=identity_key,
                        channel="root.ai",
                        description=self.env._(
                            "Process AI messages for room %(room_name)s",
                            room_name=room.name,
                        ),
                    )._job_process_room_messages()

        return messages

    def _job_process_room_messages(self):
        self.ensure_one()
        room = self.room_id

        if not room.ai_enabled:
            return

        room_messages = self.search(
            [
                ("room_id", "=", room.id),
                ("ai_processing_state", "in", ["pending", "failed"]),
            ],
            order="create_date asc",
        )

        if not room_messages:
            return

        processing_count = self.search_count(
            [
                ("room_id", "=", room.id),
                ("ai_processing_state", "=", "processing"),
            ]
        )

        if processing_count > 0:
            return

        try:
            room_messages.write(
                {
                    "ai_processing_state": "processing",
                    "ai_processing_date": fields.Datetime.now(),
                }
            )

            agent = (
                room.ai_agent_id
                if room.ai_agent_id
                else self.env["chatroom.ai.agent"].search(
                    [("active", "=", True)], limit=1
                )
            )

            audio_messages = room_messages.filtered(
                lambda m: m.message_type == "audio" and m.direction == "incoming"
            )
            for audio_msg in audio_messages.sorted("create_date", reverse=False):
                if (
                    not audio_msg.is_transcribed
                    and not audio_msg.is_transcription_failed
                ):
                    audio_msg.write({"is_transcribing": True})
                    audio_msg._notify_message_created()

                    if agent:
                        transcription = agent._transcribe_audio(audio_msg)
                        if transcription:
                            audio_msg.write(
                                {
                                    "body": transcription,
                                    "is_transcribing": False,
                                    "is_transcribed": True,
                                }
                            )
                            audio_msg._notify_message_created()
                        else:
                            audio_msg.write(
                                {
                                    "is_transcribing": False,
                                    "is_transcription_failed": True,
                                }
                            )

            if not agent:
                _logger.warning(
                    "No AI agent found for room '%s' (ID=%d)",
                    room.name,
                    room.id,
                )
                return

            if not agent.should_respond_to_room(room):
                return

            conversation = agent.get_or_create_conversation(room)
            has_unsupported_messages = False

            for message in room_messages.sorted("create_date", reverse=False):
                if message.message_type not in ["text", "audio"]:
                    has_unsupported_messages = True
                    continue

                if message.message_type == "audio" and message.is_transcription_failed:
                    continue

                conversation.add_message(message)

            if conversation.message_count > 0:
                agent._generate_and_send_response(conversation.id)

            if has_unsupported_messages and agent.unsupported_media_message:
                self.env["chatroom.message"].sudo().create(
                    {
                        "room_id": room.id,
                        "body": agent.unsupported_media_message,
                        "direction": "outgoing",
                        "user_id": self.env.ref("base.user_admin").id,
                        "author_name": agent.name,
                        "is_ai_generated": True,
                    }
                )

            room_messages.write(
                {
                    "ai_pending_processing": False,
                    "ai_processing_state": "completed",
                    "ai_processing_error": False,
                }
            )

        except Exception as e:
            error_msg = str(e)
            _logger.error(
                "Error processing AI messages for room %d: %s",
                room.id,
                error_msg,
                exc_info=True,
            )

            room_messages.write(
                {
                    "ai_processing_state": "failed",
                    "ai_processing_error": error_msg[:500],
                    "ai_pending_processing": False,
                }
            )

            room.write({"needs_attention": True})
            raise

    def _get_message_text_with_author(self):
        self.ensure_one()

        if self.is_ai_generated:
            return self.body

        return super()._get_message_text_with_author()

    def _notify_message_created(self):
        self.ensure_one()

        payload = {
            "id": self.id,
            "room_id": self.room_id.id,
            "body": self.body,
            "direction": self.direction,
            "author_name": self.author_name,
            "message_type": self.message_type,
            "create_date": self.create_date.isoformat() if self.create_date else False,
            "is_internal": self.is_internal,
            "is_ai_generated": self.is_ai_generated,
            "is_transcribing": self.is_transcribing,
            "is_transcribed": self.is_transcribed,
            "is_transcription_failed": self.is_transcription_failed,
        }

        try:
            chatroom_user_group = self.env.ref("chatroom.group_chatroom_user")
            chatroom_users = getattr(
                chatroom_user_group, "all_user_ids", chatroom_user_group.users
            )
        except Exception as e:
            _logger.error("Error getting chatroom users: %s", e)
            chatroom_users = self.env["res.users"]

        try:
            chatroom_manager_group = self.env.ref("chatroom.group_chatroom_manager")
            chatroom_managers = getattr(
                chatroom_manager_group,
                "all_user_ids",
                chatroom_manager_group.users,
            )
        except Exception as e:
            _logger.error("Error getting chatroom managers: %s", e)
            chatroom_managers = self.env["res.users"]

        users_to_notify = chatroom_managers
        if self.room_id.assigned_to_id:
            if self.room_id.assigned_to_id in chatroom_users:
                users_to_notify |= self.room_id.assigned_to_id
        else:
            users_to_notify |= chatroom_users - chatroom_managers

        notified_partners = set()
        for user in users_to_notify:
            if user.partner_id and user.partner_id.id not in notified_partners:
                notified_partners.add(user.partner_id.id)
                user.partner_id._bus_send("chatroom/message_created", payload)

        self.room_id._notify_room_updated()
