{
    "name": "ChatRoom",
    "version": "19.0.1.0.0",
    "category": "Services/ChatRoom",
    "summary": "Manage customer conversations and chat rooms",
    "author": "Nowi",
    "website": "https://nowi.com.ar",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "bus",
        "mail",
        "contacts",
    ],
    "data": [
        "data/ir_module_category_data.xml",
        "security/chatroom_security.xml",
        "security/ir.model.access.csv",
        "views/chatroom_room_views.xml",
        "views/chatroom_message_views.xml",
        "views/chatroom_menus.xml",
        "views/res_partner_views.xml",
        "views/res_config_settings_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "chatroom/static/src/components/**/*.js",
            "chatroom/static/src/components/**/*.xml",
            "chatroom/static/src/components/**/*.scss",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
