{
    "name": "ChatRoom AI Agents",
    "version": "18.0.1.0.0",
    "category": "Services/ChatRoom",
    "summary": "AI-powered agents for automated customer conversations",
    "author": "Nowi",
    "website": "https://nowi.com.ar",
    "license": "LGPL-3",
    "depends": [
        "chatroom",
        "queue_job",
        "web",
    ],
    "external_dependencies": {
        "python": [
            "PyPDF2",
            "python-docx",
            "pandas",
            "openpyxl",
            "xlrd",
        ],
    },
    "data": [
        "security/chatroom_ai_security.xml",
        "security/ir.model.access.csv",
        "data/queue_job_data.xml",
        "views/chatroom_ai_provider_views.xml",
        "views/chatroom_ai_agent_views.xml",
        "views/chatroom_ai_knowledge_views.xml",
        "views/chatroom_ai_tool_views.xml",
        "views/chatroom_ai_conversation_views.xml",
        "views/chatroom_room_views.xml",
        "views/chatroom_message_views.xml",
        "views/res_config_settings_views.xml",
        "wizard/chatroom_ai_tool_test_wizard_views.xml",
        "views/chatroom_menus.xml",
    ],
    "demo": [],
    "assets": {
        "web.assets_backend": [
            "chatroom_ai/static/src/**/*.js",
            "chatroom_ai/static/src/**/*.xml",
            "chatroom_ai/static/src/**/*.scss",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
